model_variants:
  default:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    objective: "binary:logistic"

  variant_1:
    max_depth: 4
    learning_rate: 0.05
    n_estimators: 200
    objective: "binary:logistic"

  variant_2:
    max_depth: 5
    learning_rate: 0.2
    colsample_bytree: 0.8
    min_child_weight: 5
    subsample: 0.9
    objective: "binary:logistic"
